image: artifactory.a-us-common.wfk8s.com/docker/core-platform/gitlab-runner:latest

stages:
  - build-pages
  
pages:
  stage: build-pages
  script:
    - yarn
    - yarn build
    - rm -rf public
    - mv build public
  artifacts:
    paths:
      - public
