image: artifactory.a-us-common.wfk8s.com/docker/core-platform/gitlab-runner:latest

stages:
  - build-and-test
  - publish-pages

build:
  stage: build-and-test
  script:
    - yarn
    - yarn test:coverage
  
pages:
  stage: publish-pages
  script:
    - yarn
    - yarn build
    - rm -rf public
    - mv build public
  artifacts:
    paths:
      - public
